name: Deploy to Azure

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, uat, prod]
        
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Workspace Select'
        run: terraform workspace select ${{ matrix.environment }} || terraform workspace new ${{ matrix.environment }}

      - name: 'Terraform Plan'
        run: terraform plan -var="environment=${{ matrix.environment }}" -out=plan.tfplan

      - name: 'Terraform Apply'
        run: terraform apply -input=false plan.tfplan

      - name: 'Terraform Workspace Select default'
        if: always()
        run: terraform workspace select default